apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: my-quark-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhn-support-csears/my-quark-app:3db3b3b1174ed191b00b2b1054f41e470a66cb33@sha256:317500af883b598e5a00c3a3ed7bf7cfb185849908f3eada81de864f38cf83e9
          name: container-image
